In [221]:
import pandas as pd
import re

In [132]:
#import 
shark = pd.read_csv('/Users/Eleonore/ironhack_gh/IH_Projet/Global-Shark-Attack-Incidents/GSAF5.csv', engine = 'python')
shark

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,...,NaN,"West Australian, 9/15/2016",2016.09.15.R-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.15.R,2016.09.15.R,5988,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,...,3' to 4' shark,"News4Jax, 9/11/2016",2016.09.11-PonteVedra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.11,2016.09.11,5987,NaN,NaN
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,...,"Tiger shark, 10?","Hawaii News Now, 9/7/2016",2016.09.07-Oahu.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.07,2016.09.07,5986,NaN,NaN
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,...,NaN,"TVANouvelles, 9/6/2016",2016.09.06-Jewell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.06,2016.09.06,5985,NaN,NaN
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,...,NaN,"C. Creswell, GSAF",2016.09.05.b-Williams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.b,2016.09.05.b,5984,NaN,NaN
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,...,NaN,"Perth Now, 9/5/2016",2016.09.05.a-Penman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.a,2016.09.05.a,5983,NaN,NaN
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,...,NaN,"Orlando Sentinel, 9/7/2016",2016.09.04-Moore.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.04,2016.09.04,5982,NaN,NaN
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,...,White shark,"R. Collier, GSAF",2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.01,2016.09.01,5981,NaN,NaN
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,...,"Bull shark, 6'","News Channel 8, 8/30/16",2016.08.29.b-Cumiskey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.b,2016.08.29.b,5980,NaN,NaN
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"News Channel 8, 8/30/16",2016.08.29.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.a,2016.08.29.a,5979,NaN,NaN
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,...,"Bull shark, 3.5 m","LaDepeche, 8/29/2016",2016.08.27-Chardard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.27,2016.08.27,5978,NaN,NaN
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,...,NaN,"First Coast News, 7/25/2016",2016.08.25-Cassetty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.25,2016.08.25,5977,NaN,NaN
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,...,NaN,"ABC, 8/11/2016",2016.08.07-Stoch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.07,2016.08.07,5976,NaN,NaN
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,...,"Tiger shark, 10'","SUP, 8/9/2015",2016.08.06-Baxter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.06,2016.08.06,5975,NaN,NaN
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,...,Blacktip shark,"News 965, 8/5/2016",2016.06.04-Tyler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.04,2016.08.04,5974,NaN,NaN
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,...,Blue shark,"Informacion.es, 7/29/2016",2016.07.29-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.29,2016.07.29,5973,NaN,NaN
21,2016.07.28.R,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,NaN,Swimming,Justus Franz,M,...,NaN,"Klassick, 7/28/2016",2016.07.28.R-Franz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.28.R,2016.07.28.R,5972,NaN,NaN
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,Kayaking,Ian Watkins,M,...,White shark,"ABC Australia, 7/28/2016",2016.07.28-Watkins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.28,2016.07.28,5971,NaN,NaN
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,...,"Nurse shark, 4'","Tampa Bay Times, 7/27/2016",2016.07.27-Sapp.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.27,2016.07.27,5970,NaN,NaN
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Curran See & Harry Lake,M,...,NaN,"Gold Coast Bulletin, 7/28/2016",2016.07.26-Ballina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.26,2016.07.26,5969,NaN,NaN
25,2016.07.24,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,Surfing,male,M,...,NaN,"Japan Times, 7/25/2016",2016.07.24-Japan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.24,2016.07.24,5968,NaN,NaN
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Zebulon Critchlow,M,...,NaN,"C. Black, GSAF",2016.07.23.b-Critchlow.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.23.b,2016.07.23.b,5967,NaN,NaN
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Steve Cutbirth,M,...,"Bull shark, 6'","KWTX, 7/23/2016",2016.07.23.a-Cutbirth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.23.a,2016.07.23.a,5966,NaN,NaN
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,...,"reef shark, 1m","Nine News, 7/20/2016",2016.07.20-Burck.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.20,2016.07.20,5965,NaN,NaN
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Occupant: Ben Raines,NaN,...,"Tiger shark, 10'","Al.com, 7/19/2016",2016.07.17-Gulf.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.17,2016.07.17,5964,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5962,ND.0031,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,"Aircraft ditched in the sea, swimming ashore",male,M,...,NaN,"V.M. Coppleson (1962), p.257",ND-0031-Ditched-Aircrat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0031,ND.0031,31,NaN,NaN
5963,ND.0030,Before 1905,0,Unprovoked,BURMA,NaN,NaN,Bathing,male,M,...,NaN,"Massillon Independent, 3/1905",ND-0030-Burma.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0030,ND.0030,30,NaN,NaN
5964,ND.0028,A few years before 1938,0,Boat,ITALY,Adriatic Sea,NaN,Wooden fishing boat,Occupant: Mr. Maciotta,M,...,White shark,A. De Maddalena; Anon. (1938),ND-0028-Maciotta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0028,ND.0028,29,NaN,NaN
5965,ND.0027,No date,0,Unprovoked,GREECE,Dodecanese Islands,Symi Island,Sponge diving,Psarofa-gomenes,M,...,NaN,M. N. Kalafatas,ND-0027-Psarofagomenos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0027,ND.0027,28,NaN,NaN
5966,ND.0026,Early 1930s,0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,...,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27,NaN,NaN
5967,ND.0025,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,...,NaN,H. Capper,ND-0025-Sgt-SpectacleIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0025,ND.0025,26,NaN,NaN
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,Swimming,NaN,NaN,...,NaN,G. Van Grevelynghe,ND-0024-Barachois-Reunion.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0024,ND.0024,25,NaN,NaN
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,Wading,Madelaine Dalton,F,...,NaN,"L. Green in Tavern of the Seas, p.182",ND-0023-Dalton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0023,ND.0023,24,NaN,NaN
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,Pearl diving,Jaringoorli,M,...,NaN,"Adelaide Advertiser, 1/11/1940",ND-0022-Jaringoorli.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0022,ND.0022,23,NaN,NaN
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Swimming in pool formed by construction of a w...,Indian boy,M,...,NaN,"L. Green in South African Beachcomber, p.97",ND-0021-DurbanIndianBoy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0021,ND.0021,22,NaN,NaN
5972,ND.0020,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,Great Barrier Reef,NaN,3 Japanese divers,M,...,NaN,"V.M. Coppleson (1958), p.241",ND-0020-3JapaneseDivers.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0020,ND.0020,21,NaN,NaN
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,James Kelley,M,...,NaN,"T. Helm, p.219",ND-0019-Kelley.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0019,ND.0019,20,NaN,NaN
5974,ND.0018,Before 1911,0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,V?ng T�u,Swimming around anchored ship,crewman,M,...,NaN,"Daily Kennebec Journal, 3/27/1911",ND-0018-Vietnam.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0018,ND.0018,19,NaN,NaN
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Crew swimming alongside their anchored ship,male,M,...,NaN,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0017-alongside-ship.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0017,ND.0017,18,NaN,NaN
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,4 men were bathing,male,M,...,NaN,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0016- Durban-PostOffice.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0016,ND.0016,17,NaN,NaN
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,Wreck of large double sailing canoe,20 Fijians,NaN,...,NaN,"Fijian Society papers presented April 17, 1918...",ND-0015-FijianCanoe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0015,ND.0015,16,NaN,NaN
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,"""youthful male""",M,...,NaN,"C. Creswell, GSAF; Wilmington Star, 7/17/1916",ND-0014-pre1916-NorthCarolina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0014,ND.0014,15,NaN,NaN
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,a native fisherman,M,...,NaN,"Rural New Yorker, 7/19/1913",ND-0013-Durban-native-fisherman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0013,ND.0013,14,NaN,NaN
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,a young Scotsman,M,...,NaN,"Rural New Yorker, 7/19/1913",ND-0012-Durban-Scotsman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0012,ND.0012,13,NaN,NaN
5981,ND.0011,Before 1911,0,Unprovoked,ASIA?,NaN,NaN,Swimming,Mr. Masury,M,...,NaN,"Ref. J. T. Dubois in N.Y. Sun, 3/19/1911",ND-0011-Masury.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0011,ND.0011,12,NaN,NaN
5982,ND.0010,Circa 1862,0,Unprovoked,USA,Hawaii,Puna,NaN,A chiefess,F,...,NaN,Captain W. Young,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0010,ND.0010,11,NaN,NaN
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,...,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0009-boy-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0009,ND.0009,10,NaN,NaN
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0008,ND.0008,9,NaN,NaN
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0007,ND.0007,8,NaN,NaN
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,...,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0006,ND.0006,7,NaN,NaN
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6,NaN,NaN
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5,NaN,NaN
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4,NaN,NaN
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8�N, 79�W",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

In [133]:
# to examine the base
shark.shape
# 5991 columns & 24 rows

(5992, 24)

In [134]:
shark.dtypes

Case Number               object
Date                      object
Year                       int64
Type                      object
Country                   object
Area                      object
Location                  object
Activity                  object
Name                      object
Sex                       object
Age                       object
Injury                    object
Fatal (Y/N)               object
Time                      object
Species                   object
Investigator or Source    object
pdf                       object
href formula              object
href                      object
Case Number.1             object
Case Number.2             object
original order             int64
Unnamed: 22               object
Unnamed: 23               object
dtype: object

In [135]:
#check columns
shark.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

case number : date + letter (if multiple attack on the same day)
date : attack's day : dd-mmm-yyyy
year : yyyy
type : 6 : unprovoked, provoked, boat, Sea Disaster, invalid, boating
country :
area : department, states, sea, etc.
location : beach
activity : practiced at the time of the attack
name : of the victim
sex : m & f
age : of the victim
injury : owed to the attack
fatal : yes | no
time : of the attack
species : of sharks

In [136]:
shark.Type.value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Sea Disaster     220
Boat             200
Boating          110
Name: Type, dtype: int64

# Cleaning the column names¶

to delete ponctuations, spaces, etc.

In [137]:
shark.columns = shark.columns.str.strip()
shark.columns = shark.columns.str.replace(' ', '_').str.replace(":","").str.replace("(","").str.replace(")","").str.replace("/","").str.replace(".","")
shark.columns = shark.columns.str.replace('Fatal_YN','Fatal')
shark.columns = shark.columns.str.lower()
shark.columns

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal', 'time', 'species',
       'investigator_or_source', 'pdf', 'href_formula', 'href', 'case_number1',
       'case_number2', 'original_order', 'unnamed_22', 'unnamed_23'],
      dtype='object')

# Useless columns

Name
original_order
Investigator_or_Source
pdf

In [138]:
#df = df.drop('colomns',axis=1)
shark = shark.drop('name', axis = 1).drop('original_order', axis =1).drop('investigator_or_source', axis=1).drop('pdf',axis=1)

In [139]:
shark.head()

,case_number,date,year,type,country,area,location,activity,sex,age,injury,fatal,time,species,href_formula,href,case_number1,case_number2,unnamed_22,unnamed_23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,16,Minor injury to thigh,N,13h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,36,Lacerations to hands,N,11h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,M,43,Lacerations to lower leg,N,10h43,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,NaN,NaN

#### check if columns Case_Number, Case_Number1, Case_Number2 have same information

In [140]:
case1 = (shark['case_number']==shark['case_number1'])
case2 = (shark['case_number']==shark['case_number2'])
case12 = (shark['case_number1']==shark['case_number2'])
# almost

In [141]:
case11_perc = round((case1.value_counts()/len(case1))*100,2)
case11_perc

True     99.78
False     0.22
dtype: float64

#### check if columns Case_Number, Case_Number1, Case_Number2 have same information

In [142]:
case12_perc = round((case12.value_counts()/len(case12))*100,2)
case12_perc

True     99.82
False     0.18
dtype: float64

#### they are similar, i can drop Case_Number1 and Case_Number2

In [143]:
shark = shark.drop('case_number1', axis = 1).drop('case_number2', axis = 1)

#### check if columns href_formula and href have same information

In [144]:
href = (shark['href_formula']==shark['href'])
href_perc = round((href.value_counts()/len(href))*100,2)
href_perc

True     99.1
False     0.9
dtype: float64

#### they are similar, i can drop href_formula

In [145]:
shark = shark.drop('href_formula', axis = 1)

#### check if columns Unnamed_22 and Unnamed_23 have same information

In [146]:
unnamed = (shark['unnamed_22']==shark['unnamed_23'])
unnamed_perc = round((unnamed.value_counts()/len(unnamed))*100,2)
unnamed_perc

False    100.0
dtype: float64

#### check if they countain information

In [147]:
null_cols = shark.isnull().sum()
drop_percentage = round(null_cols[null_cols>0]/shark.shape[0]*100,2)
drop_percentage

country        0.72
area           6.71
location       8.28
activity       8.80
sex            9.46
age           44.74
injury         0.45
fatal          0.32
time          53.62
species       48.97
href           0.05
unnamed_22    99.98
unnamed_23    99.97
dtype: float64

#### they are 99% empty, so they can be dropped

In [148]:
shark = shark.drop('unnamed_22', axis = 1).drop('unnamed_23', axis = 1)

# clean information

In [149]:
shark.isnull().sum()

case_number       0
date              0
year              0
type              0
country          43
area            402
location        496
activity        527
sex             567
age            2681
injury           27
fatal            19
time           3213
species        2934
href              3
dtype: int64

#### country

In [150]:
shark.country.value_counts()

USA                           2116
AUSTRALIA                     1279
SOUTH AFRICA                   565
PAPUA NEW GUINEA               133
NEW ZEALAND                    125
BRAZIL                         102
BAHAMAS                         98
MEXICO                          81
ITALY                           71
FIJI                            62
PHILIPPINES                     59
REUNION                         57
NEW CALEDONIA                   51
MOZAMBIQUE                      44
CUBA                            42
SPAIN                           40
INDIA                           37
EGYPT                           36
CROATIA                         34
JAPAN                           32
PANAMA                          32
SOLOMON ISLANDS                 29
IRAN                            29
GREECE                          25
HONG KONG                       24
JAMAICA                         23
FRENCH POLYNESIA                22
INDONESIA                       20
ENGLAND                         19
PACIFIC OCEAN                   17
                              ...
BRITISH WEST INDIES              1
GEORGIA                          1
Seychelles                       1
BANGLADESH                       1
 PHILIPPINES                     1
SOLOMON ISLANDS / VANUATU        1
CURACAO                          1
ARGENTINA                        1
SWEDEN                           1
TUVALU                           1
MEXICO                           1
BRITISH ISLES                    1
RED SEA                          1
GREENLAND                        1
WESTERN SAMOA                    1
OCEAN                            1
MEDITERRANEAN SEA?               1
SLOVENIA                         1
BRITISH VIRGIN ISLANDS           1
PUERTO RICO                      1
BAY OF BENGAL                    1
RED SEA / INDIAN OCEAN           1
GRAND CAYMAN                     1
MID-PACIFC OCEAN                 1
ADMIRALTY ISLANDS                1
ANDAMAN / NICOBAR ISLANDAS       1
MONACO                           1
IRAN / IRAQ                      1
SUDAN?                           1
ASIA?                            1
Name: country, Length: 203, dtype: int64

In [151]:
print(set(shark['country']))

{nan, 'VIETNAM', 'BRITISH VIRGIN ISLANDS', 'URUGUAY', 'ASIA?', 'MADAGASCAR', 'PUERTO RICO', 'MAURITIUS', 'MONTENEGRO', 'BRAZIL', 'SOLOMON ISLANDS', 'MICRONESIA', 'NEW BRITAIN', 'JAPAN', 'INDIAN OCEAN', 'FALKLAND ISLANDS', ' TONGA', 'SOUTHWEST PACIFIC OCEAN', 'BAY OF BENGAL', 'RED SEA / INDIAN OCEAN', 'GRAND CAYMAN', 'ISRAEL', 'SAMOA', 'MID-PACIFC OCEAN', 'SUDAN', 'ADMIRALTY ISLANDS', 'ANDAMAN / NICOBAR ISLANDAS', 'NEW ZEALAND', 'MONACO', 'LEBANON', 'IRAN / IRAQ', 'PALESTINIAN TERRITORIES', 'PORTUGAL', 'MARSHALL ISLANDS', 'SUDAN?', 'JAMAICA', 'TURKS & CAICOS', 'GULF OF ADEN', 'CAYMAN ISLANDS', 'MOZAMBIQUE', 'GUYANA', 'FRENCH POLYNESIA', 'ENGLAND', 'DOMINICAN REPUBLIC', 'TONGA', 'CANADA', 'BANGLADESH', 'TURKEY', 'EGYPT', 'UNITED KINGDOM', 'VENEZUELA', 'GHANA', 'Seychelles', 'ECUADOR', 'BERMUDA', 'CAPE VERDE', 'ATLANTIC OCEAN', 'MALTA', 'NEW GUINEA', 'GUATEMALA', 'GABON', 'SOUTH AFRICA', 'GEORGIA', 'St Helena', 'BRITISH WEST INDIES', 'UNITED ARAB EMIRATES (UAE)', 'SPAIN', 'BURMA', 'NEVIS', 'Fiji', 'SCOTLAND', 'NAMIBIA', 'OKINAWA', 'SENEGAL', 'INDIAN OCEAN?', 'YEMEN', 'NIGERIA', 'REUNION', 'DIEGO GARCIA', 'TANZANIA', 'JOHNSTON ISLAND', 'ST. MARTIN', 'CHILE', 'KIRIBATI', 'ANTIGUA', 'KENYA', 'NORTH SEA', 'RUSSIA', 'GREECE', 'NORWAY', 'MALDIVE ISLANDS', 'ANGOLA', 'MAYOTTE', 'CARIBBEAN SEA', 'KUWAIT', 'PARAGUAY', 'EGYPT / ISRAEL', 'AZORES', 'Between PORTUGAL & INDIA', 'CUBA', 'COSTA RICA', 'SIERRA LEONE', 'ST. MAARTIN', 'NORTHERN MARIANA ISLANDS', 'ARUBA', 'BRITISH NEW GUINEA', 'IRAN', 'SOUTH CHINA SEA', 'PAPUA NEW GUINEA', 'SOUTH PACIFIC OCEAN', 'DJIBOUTI', 'NORTHERN ARABIAN SEA', 'AUSTRALIA', 'GUAM', 'IRAQ', 'PACIFIC OCEAN ', 'MARTINIQUE', 'NORTH ATLANTIC OCEAN ', 'PERSIAN GULF', 'SINGAPORE', 'VANUATU', 'Coast of AFRICA', 'IRELAND', 'TASMAN SEA', 'GREENLAND', 'NORTH ATLANTIC OCEAN', 'LIBERIA', 'LIBYA', 'FRANCE', 'FEDERATED STATES OF MICRONESIA', 'AMERICAN SAMOA', 'USA', ' PHILIPPINES', 'SOLOMON ISLANDS / VANUATU', 'GUINEA', 'RED SEA?', 'CEYLON (SRI LANKA)', 'SOUTH KOREA', 'ALGERIA', 'CURACAO', 'HAITI', 'HONDURAS', 'HONG KONG', 'PACIFIC OCEAN', 'THAILAND', 'ARGENTINA', 'NEW CALEDONIA', 'SWEDEN', 'FIJI', 'TUVALU', 'MEXICO ', 'INDIA', 'SOUTH ATLANTIC OCEAN', 'TAIWAN', 'BRITISH ISLES', 'JAVA', 'BAHREIN', 'CROATIA', 'RED SEA', 'SOMALIA', 'SYRIA', 'ITALY / CROATIA', 'BAHAMAS', 'MALAYSIA', 'SAN DOMINGO', 'CRETE', 'NETHERLANDS ANTILLES', 'PHILIPPINES', 'MID ATLANTIC OCEAN', 'EQUATORIAL GUINEA / CAMEROON', 'ITALY', 'BARBADOS', 'WESTERN SAMOA', 'THE BALKANS', 'Sierra Leone', 'EL SALVADOR', 'MEDITERRANEAN SEA', 'SEYCHELLES', 'BELIZE', 'OCEAN', 'ICELAND', 'SRI LANKA', 'INDONESIA', 'PANAMA', 'UNITED ARAB EMIRATES', 'TRINIDAD & TOBAGO', 'MEDITERRANEAN SEA?', 'SAUDI ARABIA', 'TUNISIA', 'GRENADA', 'CYPRUS', 'NORTH PACIFIC OCEAN', 'SLOVENIA', 'YEMEN ', 'NICARAGUA', 'COOK ISLANDS', 'MEXICO', 'PALAU', 'CHINA', 'NICARAGUA ', 'EGYPT ', 'COLUMBIA', 'CENTRAL PACIFIC', 'KOREA'}

In [152]:
shark['country'] = shark['country'].str.replace('?', '') # RED SEA
shark['country'] = shark['country'].str.strip() #space before / after
shark['country'] = shark['country'].str.upper() #convert lower to upper
shark['country'] = shark['country'].str.replace('\(', '')
shark['country'] = shark['country'].str.replace('\)', '')
shark['country'] = shark['country'].str.replace('UAE', '')
print(set(shark['country']))

{nan, 'VIETNAM', 'BRITISH VIRGIN ISLANDS', 'URUGUAY', 'ASIA', 'MADAGASCAR', 'PUERTO RICO', 'MAURITIUS', 'MONTENEGRO', 'BRAZIL', 'SOLOMON ISLANDS', 'MICRONESIA', 'NEW BRITAIN', 'JAPAN', 'INDIAN OCEAN', 'FALKLAND ISLANDS', 'SOUTHWEST PACIFIC OCEAN', 'BAY OF BENGAL', 'RED SEA / INDIAN OCEAN', 'GRAND CAYMAN', 'CEYLON SRI LANKA', 'ISRAEL', 'SAMOA', 'MID-PACIFC OCEAN', 'SUDAN', 'ADMIRALTY ISLANDS', 'ANDAMAN / NICOBAR ISLANDAS', 'NEW ZEALAND', 'MONACO', 'LEBANON', 'IRAN / IRAQ', 'UNITED ARAB EMIRATES ', 'PALESTINIAN TERRITORIES', 'PORTUGAL', 'MARSHALL ISLANDS', 'JAMAICA', 'TURKS & CAICOS', 'GULF OF ADEN', 'CAYMAN ISLANDS', 'MOZAMBIQUE', 'GUYANA', 'FRENCH POLYNESIA', 'ENGLAND', 'DOMINICAN REPUBLIC', 'TONGA', 'CANADA', 'BANGLADESH', 'TURKEY', 'EGYPT', 'UNITED KINGDOM', 'VENEZUELA', 'GHANA', 'ECUADOR', 'BERMUDA', 'CAPE VERDE', 'ATLANTIC OCEAN', 'MALTA', 'NEW GUINEA', 'GUATEMALA', 'GABON', 'SOUTH AFRICA', 'GEORGIA', 'BRITISH WEST INDIES', 'SPAIN', 'BURMA', 'NEVIS', 'SCOTLAND', 'NAMIBIA', 'OKINAWA', 'SENEGAL', 'YEMEN', 'NIGERIA', 'REUNION', 'DIEGO GARCIA', 'TANZANIA', 'JOHNSTON ISLAND', 'ST. MARTIN', 'CHILE', 'KIRIBATI', 'ANTIGUA', 'KENYA', 'NORTH SEA', 'BETWEEN PORTUGAL & INDIA', 'RUSSIA', 'GREECE', 'NORWAY', 'MALDIVE ISLANDS', 'ANGOLA', 'MAYOTTE', 'CARIBBEAN SEA', 'KUWAIT', 'PARAGUAY', 'EGYPT / ISRAEL', 'AZORES', 'CUBA', 'COSTA RICA', 'SIERRA LEONE', 'ST. MAARTIN', 'NORTHERN MARIANA ISLANDS', 'ARUBA', 'BRITISH NEW GUINEA', 'IRAN', 'SOUTH CHINA SEA', 'PAPUA NEW GUINEA', 'SOUTH PACIFIC OCEAN', 'DJIBOUTI', 'NORTHERN ARABIAN SEA', 'AUSTRALIA', 'GUAM', 'IRAQ', 'MARTINIQUE', 'PERSIAN GULF', 'SINGAPORE', 'VANUATU', 'IRELAND', 'TASMAN SEA', 'GREENLAND', 'NORTH ATLANTIC OCEAN', 'LIBERIA', 'LIBYA', 'FRANCE', 'FEDERATED STATES OF MICRONESIA', 'AMERICAN SAMOA', 'USA', 'SOLOMON ISLANDS / VANUATU', 'GUINEA', 'SOUTH KOREA', 'ALGERIA', 'CURACAO', 'HAITI', 'HONDURAS', 'HONG KONG', 'PACIFIC OCEAN', 'THAILAND', 'ARGENTINA', 'NEW CALEDONIA', 'SWEDEN', 'FIJI', 'TUVALU', 'SOUTH ATLANTIC OCEAN', 'INDIA', 'TAIWAN', 'BRITISH ISLES', 'JAVA', 'BAHREIN', 'CROATIA', 'RED SEA', 'SOMALIA', 'SYRIA', 'ITALY / CROATIA', 'BAHAMAS', 'MALAYSIA', 'SAN DOMINGO', 'CRETE', 'NETHERLANDS ANTILLES', 'PHILIPPINES', 'MID ATLANTIC OCEAN', 'COAST OF AFRICA', 'EQUATORIAL GUINEA / CAMEROON', 'ITALY', 'BARBADOS', 'WESTERN SAMOA', 'THE BALKANS', 'EL SALVADOR', 'MEDITERRANEAN SEA', 'SEYCHELLES', 'BELIZE', 'OCEAN', 'ICELAND', 'SRI LANKA', 'INDONESIA', 'PANAMA', 'ST HELENA', 'UNITED ARAB EMIRATES', 'TRINIDAD & TOBAGO', 'SAUDI ARABIA', 'TUNISIA', 'GRENADA', 'CYPRUS', 'NORTH PACIFIC OCEAN', 'SLOVENIA', 'NICARAGUA', 'COOK ISLANDS', 'MEXICO', 'PALAU', 'CHINA', 'COLUMBIA', 'CENTRAL PACIFIC', 'KOREA'}

#### area

In [153]:
shark.area.value_counts()

Florida                              990
New South Wales                      468
Queensland                           300
Hawaii                               282
California                           276
KwaZulu-Natal                        210
Western Cape Province                188
Western Australia                    172
Eastern Cape Province                156
South Carolina                       145
South Australia                      103
North Carolina                       100
Victoria                              81
Texas                                 71
Torres Strait                         70
Pernambuco                            70
North Island                          65
New Jersey                            49
Tasmania                              41
South Island                          39
Oregon                                28
New York                              27
Northern Territory                    23
Central Province                      22
Abaco Islands                         22
Virginia                              19
Havana Province                       18
South Province                        17
Gaza                                  16
Puerto Rico                           16
                                    ...
Muala                                  1
Istria                                 1
Ibaraki Prefecture                     1
Southern District                      1
Northlands                             1
Altagracia Province                    1
Bay of Campeche                        1
 Kikori River mouth                    1
Sfax                                   1
Cabo San Lucas                         1
North Pacific coast                    1
10�S, 142�E                            1
M�laga                                 1
Kwajalein                              1
Cyrenaica                              1
Between New Ireland & New Britain      1
Manfredonia                            1
East of the Gulf of Aqaba              1
Fife                                   1
Moray                                  1
800 miles from land                    1
Negros                                 1
Muhafazat Hadramawt                    1
Magdalena Department                   1
Tabuk Province                         1
Milne Bay  Province                    1
Santo Domingo                          1
Maine                                  1
Golfo de Venezia                       1
Bardestrand                            1
Name: area, Length: 785, dtype: int64

In [154]:
shark['area'] = shark['area'].str.strip() #space before / after
shark['area'] = shark['area'].str.upper()
shark.area.value_counts()

FLORIDA                                 991
NEW SOUTH WALES                         468
QUEENSLAND                              301
HAWAII                                  282
CALIFORNIA                              276
KWAZULU-NATAL                           210
WESTERN CAPE PROVINCE                   188
WESTERN AUSTRALIA                       172
EASTERN CAPE PROVINCE                   156
SOUTH CAROLINA                          146
SOUTH AUSTRALIA                         103
NORTH CAROLINA                          103
VICTORIA                                 83
TORRES STRAIT                            72
TEXAS                                    71
PERNAMBUCO                               70
NORTH ISLAND                             65
NEW JERSEY                               50
TASMANIA                                 41
SOUTH ISLAND                             39
NEW YORK                                 30
OREGON                                   28
NORTHERN TERRITORY                       23
ABACO ISLANDS                            22
CENTRAL PROVINCE                         22
VIRGINIA                                 19
HAVANA PROVINCE                          18
SOUTH PROVINCE                           17
PUERTO RICO                              16
GAZA                                     16
                                       ...
SOUTH ATLANTIC OCEAN                      1
PACIFIC COAST                             1
BAATAN                                    1
L'ETANG-SAL�                              1
SYRACUSE                                  1
SIMPSON BAY                               1
MORAY                                     1
MIDWAY ATOLL                              1
SURIGAO DEL NORTE                         1
GOLFO DI GENOVA IN THE LIGURIAN SEA       1
5AINT-DENIS                               1
CONSERVAT�RIA DISTRICT                    1
BA RIA-VUNG TAU  PROVINCE                 1
SAINTE-MARIE                              1
200 NM SOUTHEAST OF MANILA                1
BEAUFONDS                                 1
TERRITORY OF COCOS (KEELING) ISLANDS      1
OFF VANUA LEVU                            1
EAST NEW BRITAIN                          1
LEYTE ISLAND                              1
PROVENCE                                  1
ANDALUCIA                                 1
BANDAR MA�SHUR SEA INLET                  1
GRAND BAIE                                1
LOWER SAN JUAN RIVER                      1
SOUTHWEST COAST                           1
ISLA PROVEDENCIA                          1
MINDORO                                   1
ELQUI PROVINCE                            1
BWAGAOIA                                  1
Name: area, Length: 763, dtype: int64

#### location

In [155]:
shark.location.value_counts()

New Smyrna Beach, Volusia County                                       157
Daytona Beach, Volusia County                                           28
Myrtle Beach, Horry County                                              17
Ponce Inlet, Volusia County                                             17
Melbourne Beach, Brevard County                                         15
Durban                                                                  15
Isle of Palms, Charleston County                                        14
Boa Viagem, Recife                                                      13
Cocoa Beach, Brevard County                                             12
Ponce Inlet, New Smyrna Beach, Volusia County                           12
Mossel Bay                                                              11
Ahvaz, on the Karun River                                               11
Palm Beach, Palm Beach County                                           11
Xai Xai                                                                 10
Ormond Beach, Volusia County                                            10
Sydney                                                                  10
Singer Island, Riviera Beach, Palm Beach County                         10
Nahoon                                                                  10
Piedade                                                                 10
Cocoa Beach, Brevard  County                                            10
Sydney Harbor                                                           10
Nahoon, East London                                                      9
Jacksonville Beach, Duval County                                         9
Florida Keys, Monroe County                                              9
Boa Viagem Beach, Recife                                                 9
Near Thursday Island                                                     9
North Beach, Durban                                                      9
Brisbane River                                                           9
Sanibel Island, Lee County                                               8
Amanzimtoti                                                              8
                                                                      ...
Oomura Bay                                                               1
Zuma Beach, Santa Monica, Los Angeles County                             1
Sisi  (west coast of island)                                             1
l'Anse-Vata                                                              1
Bald Island                                                              1
Mabuiag Island, between New Guinea & Australia                           1
Near the Abrolhos Archipelago                                            1
Oahu                                                                     1
Patapsco River                                                           1
Freetown Beach                                                           1
Maha�ulepu Beach, Kauai                                                  1
We, Lifou                                                                1
Jogensfontein, Stilbaai                                                  1
Ehukai Beach Park, Sunset Beach, O'ahu                                   1
Gun Beach                                                                1
Damiscotte                                                               1
Brevard County, a mile north of Sebastian Inlet                          1
Pasikudha                                                                1
La'au Point, Moloka'i                                                    1
Hapuna Beach                                                             1
Channel between South Padre Island & Padre Island National Seashore      1
Bohusl�n                                                                 1
Jura Village                                                             1
Bataan                                                                   1
Brisant Beach                                                            1
North of main swimming area in Waterman's Bay Beach, Perth               1
Strand Beach, Kissing Point, Townsville                                  1
Parker's Point, Rottnest Island                                          1
Off Dawesville Cut                                                       1
Manning River                                                            1
Name: location, Length: 3929, dtype: int64

In [156]:
shark.location = shark.location.str.strip().str.upper()
shark.location.value_counts()

NEW SMYRNA BEACH, VOLUSIA COUNTY                          159
DAYTONA BEACH, VOLUSIA COUNTY                              31
MYRTLE BEACH, HORRY COUNTY                                 17
DURBAN                                                     17
PONCE INLET, VOLUSIA COUNTY                                17
MELBOURNE BEACH, BREVARD COUNTY                            16
ISLE OF PALMS, CHARLESTON COUNTY                           15
BOA VIAGEM, RECIFE                                         13
COCOA BEACH, BREVARD COUNTY                                12
PONCE INLET, NEW SMYRNA BEACH, VOLUSIA COUNTY              12
PIEDADE                                                    11
MOSSEL BAY                                                 11
COCOA BEACH, BREVARD  COUNTY                               11
AHVAZ, ON THE KARUN RIVER                                  11
JENSEN BEACH, MARTIN COUNTY                                11
PALM BEACH, PALM BEACH COUNTY                              11
SYDNEY                                                     10
SINGER ISLAND, RIVIERA BEACH, PALM BEACH COUNTY            10
SYDNEY HARBOR                                              10
BOA VIAGEM BEACH, RECIFE                                   10
XAI XAI                                                    10
ORMOND BEACH, VOLUSIA COUNTY                               10
NAHOON                                                     10
BRISBANE RIVER                                              9
THURSDAY ISLAND                                             9
FLORIDA KEYS                                                9
JACKSONVILLE BEACH, DUVAL COUNTY                            9
NAHOON, EAST LONDON                                         9
FLORIDA KEYS, MONROE COUNTY                                 9
NEAR THURSDAY ISLAND                                        9
                                                         ...
RUNNING WATERS BEACH, NININI POINT, KAUA'I                  1
NEAR TWIN ISLANDS OFF LANIKAI, O'AHU (EAST COAST)           1
BEAR HARBOR, MENDOCINO COUNTY                               1
DAVENPORT LIGHT, SAN MATEO COUNTY                           1
INNER HARBOR, OLONGAPO                                      1
OFF ACHUTUPPU ISLAND NEAR AILIGANDI                         1
JUNO BEACH / NORTH PALM BEACH, PALM BEACH COUNTY            1
SPESSARD HOLLAND PARK, MELBOURNE BEACH, BREVARD COUNTY      1
SAN STEFANO                                                 1
AQUADILLA                                                   1
TUNNELS SURF BREAK OFF MAKUA BEACH, KAUA'I                  1
LA POINTE-AU-SEL                                            1
SURFSIDE BEACH, HORRY  COUNTY                               1
URURUMBA, MOUTH OF KIKORI RIVER 7.45S, 144.40E              1
WILSON'S PROMONTORY, WARATAH BAY                            1
LORD HOWE ISLAND                                            1
NETTLEY BAY                                                 1
OFF CAPE POINT                                              1
OFF SANTA MONICA, LOS ANGELES COUNTY                        1
PAPAMOA BEACH, BAY OF PLENTY                                1
CODFISH ISLAND (WHENUA HAU) WEST OF STEWART ISLAND          1
MUNICIPAL BEACH, BOYTON BEACH, PALM BEACH COUNTY            1
PLAYAS DE TIJUANA                                           1
SWAMPSCOTT, ESSEX COUNTY                                    1
OFF SHANKLIN                                                1
PACIFIC GROVE, MONTEREY COUNTY                              1
ST. AUGUSTINE BEACH, ST. JOHN'S COUNTY                      1
PUNTA CARACAS                                               1
BOONOOROO                                                   1
                                                            1
Name: location, Length: 3884, dtype: int64

In [157]:
shark.fatal = shark.fatal.str.strip().str.upper()

#### fatal

In [158]:
shark.fatal.value_counts()

N          4325
Y          1552
UNKNOWN      94
#VALUE!       1
F             1
Name: fatal, dtype: int64

In [159]:
# first : clean 
shark.fatal = shark.fatal.str.strip().str.upper()
shark.fatal.value_counts()

N          4325
Y          1552
UNKNOWN      94
#VALUE!       1
F             1
Name: fatal, dtype: int64

In [160]:
shark.fatal.value_counts()

N          4325
Y          1552
UNKNOWN      94
#VALUE!       1
F             1
Name: fatal, dtype: int64

In [161]:
shark.shape

(5992, 15)

In [162]:
# second : drop useless rows
shark = shark[shark['fatal'].isin(['Y','N'])]
shark.fatal.value_counts()

N    4325
Y    1552
Name: fatal, dtype: int64

In [163]:
shark.shape

(5877, 15)

### new solution : loop to use strip for every colomns

In [164]:
import numpy as np
for i in shark.select_dtypes([np.object]):
    shark[i] = shark[i].str.strip()

In [165]:
shark.head()

,case_number,date,year,type,country,area,location,activity,sex,age,injury,fatal,time,species,href
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,FLORIDA,"NEW SMYRNA BEACH, VOLUSIA COUNTY",Surfing,M,16,Minor injury to thigh,N,13h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,FLORIDA,"NEW SMYRNA BEACH, VOLUSIA COUNTY",Surfing,M,36,Lacerations to hands,N,11h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,FLORIDA,"NEW SMYRNA BEACH, VOLUSIA COUNTY",Surfing,M,43,Lacerations to lower leg,N,10h43,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,VICTORIA,THIRTEENTH BEACH,Surfing,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,VICTORIA,BELLS BEACH,Surfing,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...

#### type

In [166]:
shark.type.value_counts()

Unprovoked      4327
Provoked         553
Invalid          479
Sea Disaster     219
Boat             196
Boating          103
Name: type, dtype: int64

## check isnull

In [167]:
shark.isnull().sum()

case_number       0
date              0
year              0
type              0
country          40
area            385
location        476
activity        471
sex             519
age            2584
injury            0
fatal             0
time           3111
species        2849
href              3
dtype: int64

In [168]:
# i'm dropping every colomns with more 1000 null
null_percentage = round(null_cols[null_cols>0]/shark.shape[0]*100,2)
null_percentage

country         0.73
area            6.84
location        8.44
activity        8.97
sex             9.65
age            45.62
injury          0.46
fatal           0.32
time           54.67
species        49.92
href            0.05
unnamed_22    101.94
unnamed_23    101.92
dtype: float64

### next step : check age, time and species

#### time

In [50]:
shark.time.value_counts()

Afternoon                         174
11h00                             122
Morning                           108
12h00                             107
15h00                             100
14h00                              94
16h00                              92
16h30                              72
14h30                              70
13h00                              70
17h30                              69
17h00                              63
15h30                              62
18h00                              61
11h30                              61
Night                              57
13h30                              56
10h00                              53
09h00                              46
10h30                              45
12h30                              33
Evening                            33
09h30                              31
Late afternoon                     31
07h30                              30
08h00                              28
18h30                              27
08h30                              25
19h00                              23
07h00                              20
                                 ...
Between 06h00 & 07h20               1
After 04h00                         1
Before 10h30                        1
13h51                               1
01h50                               1
Sometime between 06h00 & 08hoo      1
19h28                               1
Before 07h00                        1
15h19                               1
13h24                               1
Mid-morning                         1
13h35                               1
09h30 / 15h30                       1
8:04 PM                             1
10h45-11h15                         1
12h38                               1
12h46                               1
17h17                               1
Midday.                             1
11h25                               1
Daytime                             1
<07h30                              1
Just before sundown                 1
05h50                               1
16h23                               1
1300                                1
19h55                               1
Mid afternoon                       1
09h57                               1
08h35                               1
Name: time, Length: 351, dtype: int64

In [169]:
shark.time

0                13h00
1                11h00
2                10h43
3                  NaN
4                  NaN
5                  NaN
6                15h15
7                14h30
8                15h40
9       Late afternoon
10      Late afternoon
11                 NaN
12                 NaN
13               15h00
14               14h00
15               17h00
16               16h00
17                 NaN
18                 NaN
19                 NaN
20               11h30
21                 NaN
22                 NaN
23                 NaN
24               12h00
25               19h05
26                 NaN
27                 NaN
28          After noon
29                 NaN
             ...
5961               NaN
5962               NaN
5963               NaN
5964               NaN
5965               NaN
5966               NaN
5968               NaN
5969               NaN
5970               NaN
5971               NaN
5972               NaN
5973               NaN
5974               NaN
5975               NaN
5976               NaN
5977               NaN
5978               NaN
5979               NaN
5980               NaN
5981               NaN
5982               NaN
5983               NaN
5984               NaN
5985               NaN
5986               NaN
5987               NaN
5988               NaN
5989               NaN
5990               NaN
5991               NaN
Name: time, Length: 5877, dtype: object

In [190]:
#create group  
shark['time'] = shark['time'].str.replace('h',':').str.replace('H',':').str.lower()
shark['time'] = shark['time'].str.replace('after noon', 'afternoon')
shark['time'] = shark['time'].str.replace('late afternoon', 'afternoon')
shark['time'] = shark['time'].str.replace('"evening"', 'evening')
shark['time'] = shark['time'].str.replace('daytime', 'afternoon')
shark['time'] = shark['time'].str.replace('late morning', 'morning')
shark['time'] = shark['time'].str.replace('nig:t', 'night')
shark['time'] = shark['time'].str.replace('midnig:t', 'night')
shark['time'] = shark['time'].str.replace('dusk', 'evening')
shark['time'] = shark['time'].str.replace('early morning', 'morning')
shark['time'] = shark['time'].str.replace('p.m.', 'afternoon')
shark['time'] = shark['time'].str.replace('a.m.', 'morning')
shark['time'] = shark['time'].str.replace('midday', 'afternoon')
shark['time'] = shark['time'].str.replace('early afternoon', 'afternoon')

In [171]:
shark.time.value_counts()

afternoon                         208
11:00                             122
morning                           109
12:00                             107
15:00                             100
14:00                              94
16:00                              92
16:30                              72
13:00                              70
14:30                              70
17:30                              69
17:00                              63
15:30                              62
11:30                              61
18:00                              61
nig:t                              58
13:30                              56
10:00                              53
09:00                              46
10:30                              45
evening                            34
12:30                              33
09:30                              31
07:30                              30
08:00                              28
18:30                              27
08:30                              25
19:00                              23
07:00                              20
17:15                              18
                                 ...
500                                 1
"after dark"                        1
11:00 / 11:30                       1
18:12                               1
15:52                               1
08:57                               1
11:01 -time of s:ip sinking         1
sometime between 06:00 & 08:oo      1
16:18                               1
19:55                               1
after midnig:t                      1
14:00 - 15:00                       1
15:06                               1
11:06                               1
19:00-20:00                         1
08:58                               1
12:48                               1
11:51                               1
10:27                               1
09:05                               1
09:00 -10:00                        1
just before dawn                    1
12:54                               1
17:11                               1
s:ortly after midnig:t              1
02:45                               1
13:51                               1
10:30 or 13:30                      1
12:00 to 14:00                      1
17:01                               1
Name: time, Length: 341, dtype: int64

#### create a fonction to group time

In [191]:
import re 

def timeto(t):
    if (re.search('[0][5-9]:',t)) or (re.search('[1][0-1]:',t)):
        t = 'morning'
    elif re.search('[1][2-7]:',t):
        t = 'afternoon'
    elif (re.search('[1][8-9]:',t)) or (re.search('[2][0-1]:',t)):
        t = 'evening'
    elif (re.search('[2][2-4]:',t)) or (re.search('[0][1-4]:',t)):
        t = 'night'
    return t

In [192]:
shark['time'] = shark['time'].apply(lambda x : timeto(x) if pd.isnull(x) == False else np.nan)

In [195]:
shark = shark[shark['time'].isin(['morning','afternoon','evening','night'])]

In [196]:
shark.time.value_counts()

afternoon    1488
morning       869
evening       252
night          95
Name: time, dtype: int64

#### age

In [220]:
shark.age.value_counts()

19                 103
18                  98
17                  90
16                  89
20                  88
15                  87
22                  82
21                  76
25                  71
24                  70
13                  61
14                  58
28                  53
29                  52
26                  51
27                  51
23                  50
30                  47
12                  40
40                  40
35                  39
31                  38
32                  37
38                  34
10                  33
36                  30
34                  29
42                  28
43                  27
39                  27
                  ...
18 or 20             1
33 or 37             1
31 or 33             1
30 or 36             1
13 or 14             1
74                   1
? & 19               1
�                    1
mid-30s              1
>50                  1
12 or 13             1
F                    1
84                   1
67                   1
21, 34,24 & 35       1
60's                 1
40s                  1
8 or 10              1
73                   1
60s                  1
9 or 10              1
13 or 18             1
(adult)              1
86                   1
25 or 28             1
MAKE LINE GREEN      1
33 & 26              1
21 or 26             1
36 & 26              1
30 & 32              1
Name: age, Length: 106, dtype: int64

#### species

In [200]:
shark['species'] = shark['species'].str.lower().str.strip()

In [201]:
shark.species.value_counts() #1433

white shark                                                                     258
spinner shark                                                                    76
bull shark                                                                       73
tiger shark                                                                      54
shark involvement not confirmed                                                  35
4' shark                                                                         34
1.8 m [6'] shark                                                                 25
4' to 5' shark                                                                   19
6' shark                                                                         19
3' to 4' shark                                                                   18
3' shark                                                                         17
5' shark                                                                         14
1.2 m [4'] shark                                                                 14
1.5 m [5'] shark                                                                 14
blue shark                                                                       12
mako shark                                                                       11
1.2 m to 1.5 m [4' to 5'] shark                                                  11
3 m [10'] shark                                                                  10
2 m shark                                                                        10
no shark involvement                                                             10
3 m shark                                                                         9
raggedtooth shark                                                                 9
2.4 m [8'] shark                                                                  8
blacktip shark                                                                    8
1.5 m shark                                                                       8
unidentified species                                                              8
"a small shark"                                                                   7
2' to 3' shark                                                                    7
12' shark                                                                         6
zambesi shark                                                                     6
                                                                               ...
1.2 m to 1.5 m [4' to 5']   shark                                                 1
"reef shark"                                                                      1
0.9 m to 1.2 m [3' to 4'] shark; tooth fragment recovered from hand               1
reef shark, 1.5m                                                                  1
tiger shark, 4.8 m                                                                1
2.7 m [9'] shark with black-tipped pectoral fins                                  1
tiger shark, 3 m to 4.9 m [10' to 16']                                            1
white shark, 13'                                                                  1
[4' to 5']                                                                        1
43" shark                                                                         1
blue shark, 1m                                                                    1
unidentified                                                                      1
white shark, 2 m to 4 m [6'9" to 13']                                             1
bull shark, 2.8 to 3.1 m                                                          1
white shark, 4 to 5 m                                                             1
white shark, 2 m                                                                  1
2 m [6.75'] sevengill  shark                                                      1
mako shark, 90kg                                                                  1
4.9 m [16'] shark                                                                 1
2 m to 2.5 m [6.75'  to 8.25'] sixgill or sevengill shark                         1
1.2 m to 1.5 m [4' to 5'] hammerhead shark                                        1
white shark, 1.8 m [6']                                                           1
1' to 2' hammerhead or bonnethed shark                                            1
3.7 m to 4.6 m [12' to 15'] shark                                                 1
wobbegong shark, 1.2 m [4'] k                                                     1
3 m to 4.3 m [10' to 14'] shark                                                   1
unknown, but it was reported that a shark tooth was recovered from the wound      1
sandbar shark, 3' to 4'                                                           1
broadnose sevengill shark                                                         1
1.8 m [6'] reef shark - or a 2.1 m to 2.4 m [7' to 8'] grey-colored shark         1
Name: species, Length: 693, dtype: int64

In [216]:
def spec(p):
    if re.search('white',p):
        p = 'white shark'
    elif re.search('tiger',p):
        p = 'tiger shark'
    elif re.search('bull',p):
        p = 'bull shark'
    elif re.search('wobbegong',p):
        p = 'wobbegong shark'
    elif re.search('mako',p):
        p = 'mako shark'
    elif re.search('raggedtooth',p):
        p = 'raggedtooth shark'
    elif re.search('blue',p):
        p = 'blue shark'
    elif re.search('spinner',p):
        p = 'spinner shark'
    elif re.search('whaler',p):
        p = 'whaler shark'
    elif re.search('blacktip',p):
        p = 'blacktip reef shark'
    else :
        p = 'unidentified shark species '
    return p
shark['species'] = shark['species'].apply(lambda x : spec(x) if pd.isnull(x) == False else np.nan)

In [217]:
shark.species.value_counts() #1433

unidentified shark species     796
white shark                    438
tiger shark                    165
bull shark                     114
spinner shark                   80
blacktip reef shark             53
raggedtooth shark               29
mako shark                      24
blue shark                      19
wobbegong shark                 17
Name: species, dtype: int64

#### activity

In [53]:
shark.activity.value_counts()

Surfing                                                                        65
Swimming                                                                       61
Fishing                                                                        29
Bathing                                                                        20
Wading                                                                         14
Spearfishing                                                                   14
Diving                                                                         11
Snorkeling                                                                      7
Standing                                                                        4
Boogie boarding                                                                 4
Body boarding                                                                   4
Scuba diving                                                                    4
Body surfing                                                                    3
Free diving                                                                     2
Kayak Fishing                                                                   2
Fell overboard                                                                  2
Boogie Boarding                                                                 2
Jet skiing                                                                      2
Windsurfing                                                                     2
Paddle boarding                                                                 2
Diving for beche-de-mer                                                         2
Kayaking                                                                        2
Freediving                                                                      2
Diving from dinghy for trochus shell                                            1
Sea disaster                                                                    1
Floating with life preserver after his boat foundered                           1
Paddling                                                                        1
Fishing, stepped on hooked shark's head                                         1
Reviving a sedated shark                                                        1
Swimming alongside yacht Mexico Fiesta                                          1
                                                                               ..
Standing / Surfing                                                              1
Crossing the bay at the ford                                                    1
Fishing boat capsized                                                           1
Swimming along side N.E.L. vessel Saluda                                        1
Washing cooking pans                                                            1
Swimming or paddle boarding                                                     1
Fell into the water                                                             1
Sea Disaster Sinking of ferryboat Christina                                     1
Fell from his father's back into the water                                      1
Wading after stray fish from seine netter�s catch                               1
Kayaking (returning from spearfishing)                                          1
Collecting aquarium specimens                                                   1
Swimming / Wading                                                               1
Diving off jetty                                                                1
Fishing for white sharks                                                        1
Underwater photography                                                          1
Chumming for white sharks                                                       1
Crouching in the water                                                          1
Kite surfing                                                                    1
Playing in the surf                                                             1
Swimming, naked                                                                 1
Feeding a shark                                                                 1
Ship Mariston torpedoed & sunk                                                  1
Fell off surf ski                                                               1
Wading to dinghy, carrying his son                                              1
Fishing, fell in water & swimming strongly to shore                             1
Bathing near whaling ship (bark A. R. Tucker of New Bedford, Massachusetts)     1
Jumping                                                                         1
Canoeing                                                                        1
Seine netting                                                                   1
Name: activity, Length: 107, dtype: int64

In [ ]:
def sport(s):
    if (re.search('surf',s)) | (('surfing',s):
        s = 'surf'
    elif